config/routes.rb
Culini::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  ### Portal
  scope(:module => :shop, :constraints => { :host => /^(www\.)*culini/ }) do
    resource  :search, :only => [:show] do
      get :autocomplete
    end
    resources :pages do
      post :preview, :on => :collection
    end
    resources :users, :constraints => { :id => /\d+/ }, :only => [:index,:show]
    resources :user_addresses do
        put :set_as_default, :on => :member
    end
    resources :faxes
    resources :delayed_jobs
    resource :stores
    root :to => "Searches#show"
    #match "/categories" => redirect("/")
  end

  ### Store
  scope :module => :shop, :path => '(:store_id)', :store_id => /\d+/ do
    #match 'css/:id' => 'designs#css'
    resources :category_images, :reservations, :store_hours, :themes
    resource :cart
    resources :cart_articles, :only => [:create,:destroy,:edit] do
      put :inc, :on => :member
      put :dec, :on => :member
      put :cycle, :on => :member
      resources :cart_extras, :only => [:index,:create,:destroy]
    end
    resource :checkout do
      get :search
    end
    resources :categories do
      get :first, :on => :collection
      put :sort, :on => :collection
      resources :articles, :extras do
        put :sort, :on => :collection
      end
    end
    resource :design do
      get :screen
    end
    resource :info
    resources :orders do
      get :status, :on => :member
      get :preview, :on => :member
      post :interfax_callback, :on => :collection
    end
    #match 'categories', :to => "Categories#index", :as => :user_root
    root :to => "Categories#index"
  end

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)
end

app/models/article.rb
class Article < ActiveRecord::Base
  # Extensions
  acts_as_list :scope => :category

  # Security
  attr_accessible :code, :name, :description,
                  :variant_1_price, :variant_2_price,
                  :variant_3_price, :variant_4_price

  # Associations & Scopes
  belongs_to  :category
  has_many :cart_articles, :dependent => :destroy
  scope :ordered, order('position')

  # Validations
  validates_presence_of :name
  validates_uniqueness_of :code, :allow_nil => true, :allow_blank => true, :scope => :category_id

  def article_variants
    [].tap do |variant|
      variant << ArticleVariant.new(variant_1_price,1) if category.category_variants.size >= 1
      variant << ArticleVariant.new(variant_2_price,2) if category.category_variants.size >= 2
      variant << ArticleVariant.new(variant_3_price,3) if category.category_variants.size >= 3
      variant << ArticleVariant.new(variant_4_price,4) if category.category_variants.size >= 4
    end
  end

  def price(variant_nr)
    send("variant_#{variant_nr}_price")
  end

  def name_with_code
    "#{name}#{(code.blank?)? "" : " ("+code+")"}"
  end

  def self.new_with_guess_article_code(*args)
    new(args) do |article|
      if last_article = article.category.articles.ordered.last
        article.variant_1_price = last_article.variant_1_price
        article.variant_2_price = last_article.variant_2_price
        article.variant_3_price = last_article.variant_3_price
        article.variant_4_price = last_article.variant_4_price
        article.code = last_article.next_code
      end
    end
  end

  def next_code()
    return nil unless code.present?
    "".tap do |str|
      str << ((code.to_i||0)+1).to_s
      str << "." if code.last == "."
    end
  end

  def self.reorder(ids)
    update_all(['position = FIND_IN_SET(id, ?)', ids.join(',')],{ :id => ids })
  end

  def to_tag(variant)
    id.to_s + "_" + variant.to_s
  end

  def as_json(options={})
    { :id => id, :name => name, :code => code, :description => description, :prices => article_variants.map(&:price) }
  end
end

app/controllers/shop/articles_controller.rb
class Shop::ArticlesController < ApplicationController
  load_and_authorize_resource :category, :through => :current_store
  load_and_authorize_resource :article, :through => :category
  respond_to :html, :json, :js

  def show
    respond_with(@article)
  end

  def new
    @article = @category.articles.new_with_guess_article_code
  end

  def create
    @article = @category.articles.create(params[:article])
  end

  def update
    @article.update_attributes(params[:article])
  end

  def destroy
    @article.destroy
  end

  def sort
    @category.articles.reorder(params[:article])
    render :nothing => true
  end

end

app/controllers/shop/cart_articles_controller.rb
class Shop::CartArticlesController < ApplicationController
  load_resource :through => :current_cart

  def create
    @cart_article = current_cart.cart_articles.create do |cart_article|
      cart_article.article_id = params[:article][:id]
      cart_article.variant    = params[:article][:variant]
    end
  end

  def inc
    @cart_article.increment_quantity!
  end

  def dec
    @cart_article.decrement_quantity!
  end

  def cycle
    @cart_article.cycle_variant!
  end

  def destroy
    @cart_article.destroy
  end

end

app/controllers/shop/cart_extras_controller.rb
class Shop::CartExtrasController < ApplicationController
  load_resource :cart_article, :through => :current_cart
  load_resource :cart_extra, :through => :cart_article

  def create
    @cart_extra = @cart_article.cart_extras.create do |cart_extra|
      cart_extra.extra_id = params[:extra][:id]
    end
  end

  def inc
    @cart_article.increment_quantity!
  end

  def dec
    @cart_article.decrement_quantity!
  end

  def destroy
    @cart_extra.destroy
  end

end

app/controllers/shop/carts_controller.rb
class Shop::CartsController < ApplicationController

  def show
    @cart = current_cart
    #fresh_when(:etag => @cart, :last_modified => @cart.updated_at.utc)
  end

  def destroy
    current_cart.destroy
    respond_with current_cart, :location => root_url
  end

end

app/controllers/shop/categories_controller.rb
class Shop::CategoriesController < ApplicationController
  load_and_authorize_resource :through => :current_store
  respond_to :html, :json, :only => [:index, :show]

  def index
    return if can?(:edit,@category)
    @category = current_store.categories.ordered.roots.first
    render "show"
  end

  def new
    @category = current_store.categories.build
  end

  def first
    return if can?(:edit,@category)
    @category = current_store.categories.ordered.roots.first
    render "show"
  end

  def show
    redirect_to @category.parent if @category.parent
  end

  def create
    @category = current_store.categories.create(params[:category])
  end

  def update
    @category.update_attributes(params[:category])
  end

  def destroy
    @category.destroy
    redirect_to @category.root
  end

  def sort
    current_store.categories.reorder(params[:category])
    render :nothing => true
  end

end

app/controllers/shop/category_images_controller.rb
class Shop::CategoryImagesController < ApplicationController
  load_and_authorize_resource

  def index
    @category_image_groups = CategoryImageGroup.ordered.includes(:category_images)
  end

  def create
    @category_image.update_attributes(params[:category_image])
    respond_with @category_image, :location => category_images_path
  end

  def update
    @category_image.update_attributes(params[:category_image])
    respond_with @category_image, :location => category_images_path
  end

  def destroy
    @category_image.destroy
    respond_with @category_image
  end

end

app/controllers/shop/checkouts_controller.rb
class Shop::CheckoutsController < ApplicationController
  respond_to :json, :only => :search

  def show
    @order = Order.new(session[:order])
    render 'empty' if current_cart.empty?
  end

  def create
    return render 'empty' if current_cart.empty?
    session[:order] = params[:order]
    @order = current_store.orders.build(session[:order]) do |order|
      order.cart_id    = current_cart.id
      order.ip_address = request.remote_ip
    end
    if @order.save
      redirect_to [:status,@order]
    else
      render "show"
    end
  end

  def search
    @zone = Zone.where(["postcode =?",params[:postcode]]).first
    respond_with(@zone)
  end

end

app/controllers/shop/delayed_jobs_controller.rb
class Shop::DelayedJobsController < ApplicationController
  load_and_authorize_resource

  def index
    @delayed_jobs = @delayed_jobs.ordered
  end

  def destroy
    @delayed_job.destroy
    respond_with @delayed_job
  end

end

app/controllers/shop/designs_controller.rb
class Shop::DesignsController < ApplicationController
  before_filter do
    @store = current_store
  end
  authorize_resource :class => "Store"

  def update
    @store.attributes = params[:store]
    @store.header = nil if params[:store][:delete_header] == "1"
    @store.save
    respond_with @store, :location => design_path
  end

  def screen
    st = render_to_string("app/stylesheets/themes/#{@store.theme.stylesheet}.sass", :layout => nil)
    render :text => Sass::Engine.new(st, :syntax => :sass, :full_exception => true, :load_paths => ["#{Rails.root}/app/stylesheets"]).render
  end

end

app/controllers/shop/extras_controller.rb
class Shop::ExtrasController < ApplicationController
  load_and_authorize_resource :category, :through => :current_store
  load_and_authorize_resource :extra, :through => :category
  respond_to :html, :json, :js

  def new
    @extra = @category.extras.new_with_guess_extra_code
  end

  def index
    @extras = @category.extras
  end

  def create
    @extra = @category.extras.create(params[:extra])
  end

  def update
    @extra.update_attributes(params[:extra])
  end

  def destroy
    @extra.destroy
  end

end

app/controllers/shop/faxes_controller.rb
#require 'interfax'
class Shop::FaxesController < ApplicationController

  def index
    authorize! :manage, Shop
    @fax_items = OrderFax.all()
  end

  def new
   authorize! :manage, Shop
   @order = Order.first
   @p = render_to_string(:partial => 'fax').to_s
  end

   def create
    authorize! :manage, Shop
    @order = Order.find(2)
    @fax = OrderFax.new(:html).contains(render_to_string(:partial => 'fax')).subject(@order.fax_subject).to("+49236189013699")
    @result = @fax.deliver
   end

end

app/controllers/shop/infos_controller.rb
class Shop::InfosController < ApplicationController
  before_filter do
    @store = current_store
  end
  authorize_resource :class => "Store", :except => [:show]

  def update
    @store.update_attributes(params[:store])
    respond_with @store, :location => info_path
  end

end

app/controllers/shop/orders_controller.rb
class Shop::OrdersController < ApplicationController
  load_and_authorize_resource :through => :current_store
  respond_to :html, :json, :only => :status

  def index
    @orders = @orders.ordered.page(params[:page]).per(20)
  end

  def preview
    render 'mailers/order_mailer/order_confirmation', :layout => nil
  end

end

app/controllers/shop/pages_controller.rb
class Shop::PagesController < ApplicationController
  load_and_authorize_resource :find_by => :handle

  def index
    @pages = @pages.ordered
  end

  def create
    @page.update_attributes(params[:page])
    respond_with @page, :location => page_path(@page.handle)
  end

  def update
    @page.update_attributes(params[:page])
    respond_with @page, :location => page_path(@page.handle)
  end

  def destroy
    @page.destroy
    respond_with @page
  end

end

app/controllers/shop/reservations_controller.rb
class Shop::ReservationsController < ApplicationController
  load_and_authorize_resource :through => :current_store

  def index
    @reservations = @reservations.ordered
  end

  def create
    @reservation.update_attributes(params[:reservation])
    respond_with @reservation
  end

  def update
    @reservation.update_attributes(params[:reservation])
    respond_with @reservation, :location => reservations_path
  end

  def destroy
    @reservation.destroy
    respond_with @reservation
  end

end

app/controllers/shop/searches_controller.rb
class Shop::SearchesController < ApplicationController
  respond_to :json

  def show
    if params[:last].present?
      @stores = Store.order('created_at').limit(params[:last])
      render 'result'
    elsif params[:q].present?
      @zones = Zone.search(params[:q])
      @zone_ids = @zones.map(&:id)
      @stores = Store.in_zones(@zone_ids)
      @stores = @stores.with_reservations_enabled if params[:reservation] == "true"
      render 'result'
    end
  end

  def autocomplete
    respond_with(Zone.autocomplete(params[:q]))
  end

end

app/controllers/shop/store_hours_controller.rb
class Shop::StoreHoursController < ApplicationController
  load_and_authorize_resource :through => :current_store

  def index
    @store_hours =  @store_hours.ordered
  end

  def create
    @store_hour.update_attributes(params[:store_hour])
    respond_with @store_hour, :location => store_hours_path
  end

  def update
    @store_hour.update_attributes(params[:store_hour])
    respond_with @store_hour, :location => store_hours_path
  end

  def destroy
    @store_hour.destroy
    respond_with @store_hour
  end

end

app/controllers/shop/stores_controller.rb
class Shop::StoresController < ApplicationController
  load_and_authorize_resource :through => :current_user

  def create
    @store.update_attributes(params[:page])
    respond_with @store, :location => categories_path(:store_id => @store)
  end

end

app/controllers/shop/themes_controller.rb
class Shop::ThemesController < ApplicationController
  load_and_authorize_resource

  def index
    @themes = @themes.ordered
  end

  def create
    @theme.update_attributes(params[:theme])
    respond_with @theme, :location => themes_path
  end

  def update
    @theme.update_attributes(params[:theme])
    respond_with @theme, :location => themes_path
  end

  def destroy
    @theme.destroy
    respond_with @theme
  end

end

app/views/shop/articles/_article.html.haml
%tr[article]{ :class => cycle(:even,:odd)}
  %td.code= article.code
  %td.name
    .article_name
      - if can?(:manage,article)
        = link_to article.name, [:edit,article.category,article], :remote => true
        &nbsp;
        = link_to image_tag('trash.png'), [article.category,article], :confirm => "Wollen Sie #{article.name} wirklich löschen?", :method => :delete, :remote => true
      - else
        = article.name
    - if article.description?
      .description= textilized_lite(article.description)

  - article.article_variants.each do |article_variant|
    %td.price= article_variant.price ? link_to_add_article(article,article_variant.number) : raw("&nbsp;")

app/views/shop/articles/_form.html.haml
%td.code
%td{ :colspan => 2+@category.category_variants.size}
  = form_for([@article.category, @article], :remote => true) do |f|
    .inputs
      = f.input :code, :input_html => { :class => (@article.category.last_article.try(:code?))? 'focus' : nil, :tabindex => 1 }
      = f.input :name, :hint => "z.B. Pizza Magaritha", :input_html => { :class => (@article.category.last_article.try(:code?))? nil : 'focus', :tabindex => 2 }
      = f.input :description, :as => :text, :input_html => { :rows => 1, :cols => 119, :tabindex => 3 }, :hint => "z.B. mit Tomatensoße und Käse"

    .inputs
      %strong Preis: &nbsp; &nbsp;
      - if @article.category.category_variants.size >= 1
        = @article.category.category_variants[0].name
        = f.text_field :variant_1_price, :size => 7, :tabindex => 4
        &nbsp;
      - if @article.category.category_variants.size >= 2
        = @article.category.category_variants[1].name
        = f.text_field :variant_2_price, :size => 7, :tabindex => 5
        &nbsp;
      - if @article.category.category_variants.size >= 3
        = @article.category.category_variants[2].name
        = f.text_field :variant_3_price, :size => 7, :tabindex => 6
        &nbsp;
      - if @article.category.category_variants.size >= 4
        = @article.category.category_variants[3].name
        = f.text_field :variant_4_price, :size => 7, :tabindex => 7
      - if @article.category.category_variants.size > 1
        = link_to "Größen verändern", edit_category_path(@article.category,:only => [:variants]), :remote => true
      - else
        = link_to "Größen hinzufügen", edit_category_path(@article.category,:only => [:variants]), :remote => true

    .actions
      = f.button :submit, :tabindex => 8
      oder
      - if @article.new_record?
        = link_to_function "Abbruch", "$('##{dom_id(@category,"new_article")}').hide();", :class => "cancel"
      - else
        = link_to "Abbruch", [@article.category, @article], :remote => true, :class => "cancel"

app/views/shop/articles/create.js.haml
- if @article.valid?
  $('#{escape_javascript(render(@article))}').appendTo('##{dom_id(@category,"articles")}').hide().fadeIn('slow');
  - @article = @category.articles.new_with_guess_article_code
  $('##{dom_id(@category,"new_article")}').html('#{escape_javascript(render("form"))}').show();
- else
  $('##{dom_id(@category,"new_article")}').html('#{escape_javascript(render("form"))}').show();


$('##{dom_id(@category,"new_article")} .focus').focus();

app/views/shop/articles/destroy.js.haml
$('##{dom_id(@article)}').fadeOut('fast', function() { $(this).remove(); });

app/views/shop/articles/edit.js.haml
$('##{dom_id(@article)}').html('#{escape_javascript(render("form"))}')
$('##{dom_id(@article)} #article_description').autoGrow();

$('##{dom_id(@article)} .focus').focus();

app/views/shop/articles/new.js.haml
$('##{dom_id(@category,"new_article")}').html('#{escape_javascript(render("form"))}').show();
$('##{dom_id(@category,"new_article")} .focus').focus();
$('##{dom_id(@category,"new_article")} #article_description').autoGrow();

app/views/shop/articles/show.js.haml
ccc = $('##{dom_id(@article)}').attr('class');
$('##{dom_id(@article)}').replaceWith('#{escape_javascript(render(@article))}');
$('##{dom_id(@article)}').removeClass("even").addClass(ccc);

app/views/shop/articles/update.js.haml
- if @article.valid?
  ccc = $('##{dom_id(@article)}').attr('class');
  $('##{dom_id(@article)}').replaceWith('#{escape_javascript(render(@article))}');
  $('##{dom_id(@article)}').removeClass("even").addClass(ccc);
- else
  $('##{dom_id(@article)}').html('#{escape_javascript(render("form"))}')